varReference:
- path: data/SAS_CERTIFICATE_SAN_DNS
  kind: ConfigMap
nameReference:
- kind: ConfigMap
  version: v1
  fieldSpecs:
  - path: spec/controllerTemplate/spec/containers/envFrom/configMapRef/name
    kind: CASDeployment
  - path: spec/controllerTemplate/spec/initContainers/envFrom/configMapRef/name
    kind: CASDeployment
  - path: spec/controllerTemplate/spec/volumes/configMap/name
    kind: CASDeployment
  - path: spec/projectTemplate/deployment/spec/template/spec/containers/envFrom/configMapRef/name
    kind: ESPConfig
  - path: spec/projectTemplate/deployment/spec/template/spec/initContainers/envFrom/configMapRef/name
    kind: ESPConfig
  - path: spec/projectTemplate/deployment/spec/template/spec/volumes/configMap/name
    kind: ESPConfig
  - path: spec/certframe/containers/envFrom/configMapRef/name
    kind: Pgcluster
  - path: spec/certframe/initContainers/envFrom/configMapRef/name
    kind: Pgcluster
  - path: spec/certframe/volumes/configMap/name
    kind: Pgcluster
- kind: Secret
  version: v1
  fieldSpecs:
  - path: data/SAS_INGRESS_CERTIFICATE_SECRET_NAME
    kind: ConfigMap
  - path: spec/projectTemplate/ingress/spec/tls/secretName
    kind: ESPConfig
  - path: spec/ingressTemplate/spec/tls/secretName
    kind: CASDeployment