# Example postgres-custom-config when default to SAS Provided Postgres custom configuration.
#   - Set on your Kubernetes cluster.
#   - Internal PostgreSQL only. 
#   - This generator does not apply if you opted for an external PostgreSQL instance. 
#   - In the following code, user-defined values are indicated by a capitalized and
#     hyphenated name set off by curly braces and a space at each end. To replace
#     the variable, replace the curly braces, interior spaces, and the variable name. 
#     For instance, 
#        {{ HBA-CONF-HOST-OR-HOSTSSL }} should be replaced by hostssl when SSL is on or host when SSL is off.
#        {{ PASSWORD-ENCRYPTION }} should be replaced by md5 or scram-sha-256.
#   - Keep all other values as is and change only as needed.

apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: postgresql-custom
behavior: merge
literals:
- |
  postgres-ha.yaml=
  ---
  bootstrap:
    dcs:
      postgresql:
        parameters:
          archive_timeout: 60                            # Added through SAS provided kustomize configMapGenerator
          checkpoint_completion_target: 0.9              # Added through SAS provided kustomize configMapGenerator
          effective_cache_size: 4GB                      # Added through SAS provided kustomize configMapGenerator
          hot_standby: on                                # Added through SAS provided kustomize configMapGenerator
          log_filename: 'postgresql_%Y%m%d%H%M%S.log'    # Added through SAS provided kustomize configMapGenerator
          log_line_prefix: '%m'                          # Added through SAS provided kustomize configMapGenerator
          log_min_duration_statement: -1                 # Added through SAS provided kustomize configMapGenerator
          log_statement: 'none'                          # Added through SAS provided kustomize configMapGenerator
          log_truncate_on_rotation: on                   # Added through SAS provided kustomize configMapGenerator
          logging_collector: on                          # Added through SAS provided kustomize configMapGenerator
          maintenance_work_mem: 128MB                    # Added through SAS provided kustomize configMapGenerator
          max_connections: 1280                          # Added through SAS provided kustomize configMapGenerator
          max_prepared_transactions: 1280                # Added through SAS provided kustomize configMapGenerator
          max_wal_senders: 8                             # Added through SAS provided kustomize configMapGenerator
          max_wal_size: 2GB                              # Added through SAS provided kustomize configMapGenerator
          min_wal_size: 80MB                             # Added through SAS provided kustomize configMapGenerator
          password_encryption: {{ PASSWORD-ENCRYPTION }} # Added through SAS provided kustomize configMapGenerator
          shared_buffers: 4GB                            # Added through SAS provided kustomize configMapGenerator
          ssl_ciphers: 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384'     # Added through SAS provided kustomize configMapGenerator
          ssl_prefer_server_ciphers: on                  # Added through SAS provided kustomize configMapGenerator
          synchronous_standby_names: ''                  # Added through SAS provided kustomize configMapGenerator
          wal_buffers: 16MB                              # Added through SAS provided kustomize configMapGenerator
          wal_keep_segments: 1000                        # Added through SAS provided kustomize configMapGenerator
          wal_level: hot_standby                         # Added through SAS provided kustomize configMapGenerator
          wal_log_hints: on                              # Added through SAS provided kustomize configMapGenerator
          work_mem: 16MB                                 # Added through SAS provided kustomize configMapGenerator
    initdb:
     - encoding: UTF8
     - no-locale
  postgresql:
    pg_hba:
      - local all postgres peer
      - local all all trust
      - local all crunchyadm peer
      - {{ HBA-CONF-HOST-OR-HOSTSSL }} replication primaryuser 0.0.0.0/0 {{ PASSWORD-ENCRYPTION }}
      - {{ HBA-CONF-HOST-OR-HOSTSSL }} all all 127.0.0.1/32 {{ PASSWORD-ENCRYPTION }}
      - {{ HBA-CONF-HOST-OR-HOSTSSL }} all all 0.0.0.0/0 {{ PASSWORD-ENCRYPTION }}