apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: sas-kerberos-config
literals:
- JAVA_OPTION_KRB5_CONF=-Djava.security.krb5.conf=/opt/kerberos/krb5.conf
- SPRING_PROFILES_ACTIVE=ldap,postgresql,kerberos
- SAS_LOGON_KERBEROS_KEYTABLOCATION=file:///opt/kerberos/keytab
- SAS_LOGON_KERBEROS_DEBUG=true
- SAS_LOGON_KERBEROS_DISABLEDELEGATIONWARNING=true
- SAS_LOGON_KERBEROS_SERVICEPRINCIPAL={{ PRINCIPAL-NAME-IN-KEYTAB }}  #change this to the principal name in the keytab
- SAS_LOGON_KERBEROS_SPN={{ SPN }}  #change this to the SPN